### ISSUE TITLE
Bug: Fix testing error for sign up unit test

### ISSUE THREAD

**Issue by Asfand00** [SeattleColleges/belindas-closet-nextjs#511]
as a dev, I want to fix the testing console errors as experienced on the reference image for the sign-up page

reference image:
![image](https://github.com/user-attachments/assets/324c9acb-c898-4a58-8f8a-05af55025eec)

did some digging into where the error is originating from and it seems to be a dependency issue with next and next/image, fetch priority is not found in any of the files and the path listed in the error, I can't seem to find it (there is no /src/client under next in node modules). It's possible that there are unrecognized props being passed down but I'm not sure since it looks like the img components are being used correctly to my knowledge. Currently trying to suppress the error if possible but not sure if that is plausible to do. Any help is appreciated on this issue.

Related: #520, refer here to see more progress on this issue.

**Comment by IsaacJrTypes** [comment]
There is a dependency issue between Next.JS and React. After investigating, I found that this was a common issue, and there are [mixed reports on whether Next.js 14.2.4](https://github.com/vercel/next.js/issues/65161#issuecomment-2191914320) fixed the problem. I downgraded React locally to 18.2, and the error disappeared. Reading through the [React release notes](https://github.com/facebook/react/releases), it looks like versions after 18.2 were released to help identify errors or deprecated API's before upgrading to React 19. It is a way to make your code compliant for upgrading, even though that is never easy, as things are guaranteed to break. Since there is no immediate need to upgrade to React 19, we can downgrade to React 18.2 to fix this issue.
